; SAFARI GNSS — RP2040 Firmware
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform        = raspberrypi
board           = pico
framework       = arduino
upload_protocol = picotool
